# Generated by Django 3.2.6 on 2025-07-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=6)),
                ('loc', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
