# Generated by Django 3.2.6 on 2025-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_event_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue', models.CharField(max_length=10)),
                ('Time_start', models.DateTimeField()),
                ('Time_end', models.DateTimeField()),
                ('Event', models.CharField(max_length=10)),
                ('Instructor', models.CharField(max_length=20)),
            ],
        ),
    ]
