# Generated by Django 3.2.6 on 2025-07-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=2)),
                ('loc', models.CharField(max_length=10)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=1, max_digits=5)),
                ('light', models.IntegerField()),
                ('snd', models.IntegerField()),
            ],
        ),
    ]
