# Generated by Django 3.2.6 on 2025-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hum',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='node_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
